bin/target6Control_writeReg 5 128
bin/target6Control_writeReg 6 320
TrigThreshold="3200"
ASICno="0"
	bin/target6Control_writeDacReg $ASICno 0    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 2    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 4    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 6    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 8    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 10   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 12   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 14   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 16   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 18   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 20   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 22   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 24   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 26   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 28   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 30   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 1    985
	bin/target6Control_writeDacReg $ASICno 3    985
	bin/target6Control_writeDacReg $ASICno 5    985
	bin/target6Control_writeDacReg $ASICno 7    985
	bin/target6Control_writeDacReg $ASICno 9    985
	bin/target6Control_writeDacReg $ASICno 11   985
	bin/target6Control_writeDacReg $ASICno 13   985
	bin/target6Control_writeDacReg $ASICno 15   985
	bin/target6Control_writeDacReg $ASICno 17   985
	bin/target6Control_writeDacReg $ASICno 19   985
	bin/target6Control_writeDacReg $ASICno 21   985
	bin/target6Control_writeDacReg $ASICno 23   985
	bin/target6Control_writeDacReg $ASICno 25   985
	bin/target6Control_writeDacReg $ASICno 27   985
	bin/target6Control_writeDacReg $ASICno 29   985
	bin/target6Control_writeDacReg $ASICno 31   985
	bin/target6Control_writeDacReg $ASICno 48   1300 
	bin/target6Control_writeDacReg $ASICno 49   0 
	bin/target6Control_writeDacReg $ASICno 50   2650 
	bin/target6Control_writeDacReg $ASICno 51   1100 
	bin/target6Control_writeDacReg $ASICno 52   1500 
	bin/target6Control_writeDacReg $ASICno 53   1062 
	bin/target6Control_writeDacReg $ASICno 54   3500 
	bin/target6Control_writeDacReg $ASICno 55   0 
	bin/target6Control_writeDacReg $ASICno 56   1152 
	bin/target6Control_writeDacReg $ASICno 57   0 
	bin/target6Control_writeDacReg $ASICno 58   2235 
	bin/target6Control_writeDacReg $ASICno 59   0 
	bin/target6Control_writeDacReg $ASICno 61   900 
	bin/target6Control_writeDacReg $ASICno 62   1100 
	bin/target6Control_writeDacReg $ASICno 63   1100 
	bin/target6Control_writeDacReg $ASICno 64   143 
	bin/target6Control_writeDacReg $ASICno 65   163 
	bin/target6Control_writeDacReg $ASICno 66   163 
	bin/target6Control_writeDacReg $ASICno 67   178 
	bin/target6Control_writeDacReg $ASICno 68   35 
	bin/target6Control_writeDacReg $ASICno 69   45 
	bin/target6Control_writeDacReg $ASICno 70   35 
	bin/target6Control_writeDacReg $ASICno 71   50 
	bin/target6Control_writeDacReg $ASICno 72   163 
	bin/target6Control_writeDacReg $ASICno 73   173 
	bin/target6Control_writeDacReg $ASICno 74   40 
	bin/target6Control_writeDacReg $ASICno 75   58 
	bin/target6Control_writeDacReg $ASICno 76   737 
	bin/target6Control_writeDacReg $ASICno 77   3112 
	bin/target6Control_writeDacReg $ASICno 78   1152 
	bin/target6Control_writeDacReg $ASICno 79   2730 

ASICno="1"
	bin/target6Control_writeDacReg $ASICno 0    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 2    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 4    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 6    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 8    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 10   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 12   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 14   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 16   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 18   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 20   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 22   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 24   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 26   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 28   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 30   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 1    985
	bin/target6Control_writeDacReg $ASICno 3    985
	bin/target6Control_writeDacReg $ASICno 5    985
	bin/target6Control_writeDacReg $ASICno 7    985
	bin/target6Control_writeDacReg $ASICno 9    985
	bin/target6Control_writeDacReg $ASICno 11   985
	bin/target6Control_writeDacReg $ASICno 13   985
	bin/target6Control_writeDacReg $ASICno 15   985
	bin/target6Control_writeDacReg $ASICno 17   985
	bin/target6Control_writeDacReg $ASICno 19   985
	bin/target6Control_writeDacReg $ASICno 21   985
	bin/target6Control_writeDacReg $ASICno 23   985
	bin/target6Control_writeDacReg $ASICno 25   985
	bin/target6Control_writeDacReg $ASICno 27   985
	bin/target6Control_writeDacReg $ASICno 29   985
	bin/target6Control_writeDacReg $ASICno 31   985
	bin/target6Control_writeDacReg $ASICno 48   1300 
	bin/target6Control_writeDacReg $ASICno 49   0 
	bin/target6Control_writeDacReg $ASICno 50   2650 
	bin/target6Control_writeDacReg $ASICno 51   1100 
	bin/target6Control_writeDacReg $ASICno 52   1500 
	bin/target6Control_writeDacReg $ASICno 53   1062 
	bin/target6Control_writeDacReg $ASICno 54   3500 
	bin/target6Control_writeDacReg $ASICno 55   0 
	bin/target6Control_writeDacReg $ASICno 56   1152 
	bin/target6Control_writeDacReg $ASICno 57   0 
	bin/target6Control_writeDacReg $ASICno 58   2235 
	bin/target6Control_writeDacReg $ASICno 59   0 
	bin/target6Control_writeDacReg $ASICno 61   900 
	bin/target6Control_writeDacReg $ASICno 62   1100 
	bin/target6Control_writeDacReg $ASICno 63   1100 
	bin/target6Control_writeDacReg $ASICno 64   143 
	bin/target6Control_writeDacReg $ASICno 65   163 
	bin/target6Control_writeDacReg $ASICno 66   163 
	bin/target6Control_writeDacReg $ASICno 67   178 
	bin/target6Control_writeDacReg $ASICno 68   35 
	bin/target6Control_writeDacReg $ASICno 69   45 
	bin/target6Control_writeDacReg $ASICno 70   35 
	bin/target6Control_writeDacReg $ASICno 71   50 
	bin/target6Control_writeDacReg $ASICno 72   163 
	bin/target6Control_writeDacReg $ASICno 73   173 
	bin/target6Control_writeDacReg $ASICno 74   40 
	bin/target6Control_writeDacReg $ASICno 75   58 
	bin/target6Control_writeDacReg $ASICno 76   737 
	bin/target6Control_writeDacReg $ASICno 77   3112 
	bin/target6Control_writeDacReg $ASICno 78   1152 
	bin/target6Control_writeDacReg $ASICno 79   2730 
	
ASICno="2"
	bin/target6Control_writeDacReg $ASICno 0    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 2    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 4    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 6    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 8    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 10   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 12   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 14   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 16   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 18   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 20   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 22   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 24   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 26   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 28   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 30   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 1    985
	bin/target6Control_writeDacReg $ASICno 3    985
	bin/target6Control_writeDacReg $ASICno 5    985
	bin/target6Control_writeDacReg $ASICno 7    985
	bin/target6Control_writeDacReg $ASICno 9    985
	bin/target6Control_writeDacReg $ASICno 11   985
	bin/target6Control_writeDacReg $ASICno 13   985
	bin/target6Control_writeDacReg $ASICno 15   985
	bin/target6Control_writeDacReg $ASICno 17   985
	bin/target6Control_writeDacReg $ASICno 19   985
	bin/target6Control_writeDacReg $ASICno 21   985
	bin/target6Control_writeDacReg $ASICno 23   985
	bin/target6Control_writeDacReg $ASICno 25   985
	bin/target6Control_writeDacReg $ASICno 27   985
	bin/target6Control_writeDacReg $ASICno 29   985
	bin/target6Control_writeDacReg $ASICno 31   985
	bin/target6Control_writeDacReg $ASICno 48   1300 
	bin/target6Control_writeDacReg $ASICno 49   0 
	bin/target6Control_writeDacReg $ASICno 50   2650 
	bin/target6Control_writeDacReg $ASICno 51   1100 
	bin/target6Control_writeDacReg $ASICno 52   1500 
	bin/target6Control_writeDacReg $ASICno 53   1062 
	bin/target6Control_writeDacReg $ASICno 54   3500 
	bin/target6Control_writeDacReg $ASICno 55   0 
	bin/target6Control_writeDacReg $ASICno 56   1152 
	bin/target6Control_writeDacReg $ASICno 57   0 
	bin/target6Control_writeDacReg $ASICno 58   2235 
	bin/target6Control_writeDacReg $ASICno 59   0 
	bin/target6Control_writeDacReg $ASICno 61   900 
	bin/target6Control_writeDacReg $ASICno 62   1100 
	bin/target6Control_writeDacReg $ASICno 63   1100 
	bin/target6Control_writeDacReg $ASICno 64   143 
	bin/target6Control_writeDacReg $ASICno 65   163 
	bin/target6Control_writeDacReg $ASICno 66   163 
	bin/target6Control_writeDacReg $ASICno 67   178 
	bin/target6Control_writeDacReg $ASICno 68   35 
	bin/target6Control_writeDacReg $ASICno 69   45 
	bin/target6Control_writeDacReg $ASICno 70   35 
	bin/target6Control_writeDacReg $ASICno 71   50 
	bin/target6Control_writeDacReg $ASICno 72   163 
	bin/target6Control_writeDacReg $ASICno 73   173 
	bin/target6Control_writeDacReg $ASICno 74   40 
	bin/target6Control_writeDacReg $ASICno 75   58 
	bin/target6Control_writeDacReg $ASICno 76   737 
	bin/target6Control_writeDacReg $ASICno 77   3112 
	bin/target6Control_writeDacReg $ASICno 78   1152 
	bin/target6Control_writeDacReg $ASICno 79   2730 

ASICno="3"
	bin/target6Control_writeDacReg $ASICno 0    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 2    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 4    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 6    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 8    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 10   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 12   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 14   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 16   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 18   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 20   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 22   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 24   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 26   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 28   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 30   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 1    985
	bin/target6Control_writeDacReg $ASICno 3    985
	bin/target6Control_writeDacReg $ASICno 5    985
	bin/target6Control_writeDacReg $ASICno 7    985
	bin/target6Control_writeDacReg $ASICno 9    985
	bin/target6Control_writeDacReg $ASICno 11   985
	bin/target6Control_writeDacReg $ASICno 13   985
	bin/target6Control_writeDacReg $ASICno 15   985
	bin/target6Control_writeDacReg $ASICno 17   985
	bin/target6Control_writeDacReg $ASICno 19   985
	bin/target6Control_writeDacReg $ASICno 21   985
	bin/target6Control_writeDacReg $ASICno 23   985
	bin/target6Control_writeDacReg $ASICno 25   985
	bin/target6Control_writeDacReg $ASICno 27   985
	bin/target6Control_writeDacReg $ASICno 29   985
	bin/target6Control_writeDacReg $ASICno 31   985
	bin/target6Control_writeDacReg $ASICno 48   1300 
	bin/target6Control_writeDacReg $ASICno 49   0 
	bin/target6Control_writeDacReg $ASICno 50   2650 
	bin/target6Control_writeDacReg $ASICno 51   1100 
	bin/target6Control_writeDacReg $ASICno 52   1500 
	bin/target6Control_writeDacReg $ASICno 53   1062 
	bin/target6Control_writeDacReg $ASICno 54   3500 
	bin/target6Control_writeDacReg $ASICno 55   0 
	bin/target6Control_writeDacReg $ASICno 56   1152 
	bin/target6Control_writeDacReg $ASICno 57   0 
	bin/target6Control_writeDacReg $ASICno 58   2235 
	bin/target6Control_writeDacReg $ASICno 59   0 
	bin/target6Control_writeDacReg $ASICno 61   900 
	bin/target6Control_writeDacReg $ASICno 62   1100 
	bin/target6Control_writeDacReg $ASICno 63   1100 
	bin/target6Control_writeDacReg $ASICno 64   143 
	bin/target6Control_writeDacReg $ASICno 65   163 
	bin/target6Control_writeDacReg $ASICno 66   163 
	bin/target6Control_writeDacReg $ASICno 67   178 
	bin/target6Control_writeDacReg $ASICno 68   35 
	bin/target6Control_writeDacReg $ASICno 69   45 
	bin/target6Control_writeDacReg $ASICno 70   35 
	bin/target6Control_writeDacReg $ASICno 71   50 
	bin/target6Control_writeDacReg $ASICno 72   163 
	bin/target6Control_writeDacReg $ASICno 73   173 
	bin/target6Control_writeDacReg $ASICno 74   40 
	bin/target6Control_writeDacReg $ASICno 75   58 
	bin/target6Control_writeDacReg $ASICno 76   737 
	bin/target6Control_writeDacReg $ASICno 77   3112 
	bin/target6Control_writeDacReg $ASICno 78   1152 
	bin/target6Control_writeDacReg $ASICno 79   2730 

ASICno="4"
	bin/target6Control_writeDacReg $ASICno 0    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 2    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 4    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 6    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 8    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 10   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 12   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 14   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 16   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 18   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 20   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 22   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 24   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 26   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 28   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 30   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 1    985
	bin/target6Control_writeDacReg $ASICno 3    985
	bin/target6Control_writeDacReg $ASICno 5    985
	bin/target6Control_writeDacReg $ASICno 7    985
	bin/target6Control_writeDacReg $ASICno 9    985
	bin/target6Control_writeDacReg $ASICno 11   985
	bin/target6Control_writeDacReg $ASICno 13   985
	bin/target6Control_writeDacReg $ASICno 15   985
	bin/target6Control_writeDacReg $ASICno 17   985
	bin/target6Control_writeDacReg $ASICno 19   985
	bin/target6Control_writeDacReg $ASICno 21   985
	bin/target6Control_writeDacReg $ASICno 23   985
	bin/target6Control_writeDacReg $ASICno 25   985
	bin/target6Control_writeDacReg $ASICno 27   985
	bin/target6Control_writeDacReg $ASICno 29   985
	bin/target6Control_writeDacReg $ASICno 31   985
	bin/target6Control_writeDacReg $ASICno 48   1300 
	bin/target6Control_writeDacReg $ASICno 49   0 
	bin/target6Control_writeDacReg $ASICno 50   2650 
	bin/target6Control_writeDacReg $ASICno 51   1100 
	bin/target6Control_writeDacReg $ASICno 52   1500 
	bin/target6Control_writeDacReg $ASICno 53   1062 
	bin/target6Control_writeDacReg $ASICno 54   3500 
	bin/target6Control_writeDacReg $ASICno 55   0 
	bin/target6Control_writeDacReg $ASICno 56   1152 
	bin/target6Control_writeDacReg $ASICno 57   0 
	bin/target6Control_writeDacReg $ASICno 58   2235 
	bin/target6Control_writeDacReg $ASICno 59   0 
	bin/target6Control_writeDacReg $ASICno 61   900 
	bin/target6Control_writeDacReg $ASICno 62   1100 
	bin/target6Control_writeDacReg $ASICno 63   1100 
	bin/target6Control_writeDacReg $ASICno 64   143 
	bin/target6Control_writeDacReg $ASICno 65   163 
	bin/target6Control_writeDacReg $ASICno 66   163 
	bin/target6Control_writeDacReg $ASICno 67   178 
	bin/target6Control_writeDacReg $ASICno 68   35 
	bin/target6Control_writeDacReg $ASICno 69   45 
	bin/target6Control_writeDacReg $ASICno 70   35 
	bin/target6Control_writeDacReg $ASICno 71   50 
	bin/target6Control_writeDacReg $ASICno 72   163 
	bin/target6Control_writeDacReg $ASICno 73   173 
	bin/target6Control_writeDacReg $ASICno 74   40 
	bin/target6Control_writeDacReg $ASICno 75   58 
	bin/target6Control_writeDacReg $ASICno 76   737 
	bin/target6Control_writeDacReg $ASICno 77   3112 
	bin/target6Control_writeDacReg $ASICno 78   1152 
	bin/target6Control_writeDacReg $ASICno 79   2730 

ASICno="5"
	bin/target6Control_writeDacReg $ASICno 0    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 2    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 4    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 6    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 8    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 10   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 12   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 14   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 16   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 18   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 20   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 22   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 24   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 26   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 28   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 30   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 1    985
	bin/target6Control_writeDacReg $ASICno 3    985
	bin/target6Control_writeDacReg $ASICno 5    985
	bin/target6Control_writeDacReg $ASICno 7    985
	bin/target6Control_writeDacReg $ASICno 9    985
	bin/target6Control_writeDacReg $ASICno 11   985
	bin/target6Control_writeDacReg $ASICno 13   985
	bin/target6Control_writeDacReg $ASICno 15   985
	bin/target6Control_writeDacReg $ASICno 17   985
	bin/target6Control_writeDacReg $ASICno 19   985
	bin/target6Control_writeDacReg $ASICno 21   985
	bin/target6Control_writeDacReg $ASICno 23   985
	bin/target6Control_writeDacReg $ASICno 25   985
	bin/target6Control_writeDacReg $ASICno 27   985
	bin/target6Control_writeDacReg $ASICno 29   985
	bin/target6Control_writeDacReg $ASICno 31   985
	bin/target6Control_writeDacReg $ASICno 48   1300 
	bin/target6Control_writeDacReg $ASICno 49   0 
	bin/target6Control_writeDacReg $ASICno 50   2650 
	bin/target6Control_writeDacReg $ASICno 51   1100 
	bin/target6Control_writeDacReg $ASICno 52   1500 
	bin/target6Control_writeDacReg $ASICno 53   1062 
	bin/target6Control_writeDacReg $ASICno 54   3500 
	bin/target6Control_writeDacReg $ASICno 55   0 
	bin/target6Control_writeDacReg $ASICno 56   1152 
	bin/target6Control_writeDacReg $ASICno 57   0 
	bin/target6Control_writeDacReg $ASICno 58   2235 
	bin/target6Control_writeDacReg $ASICno 59   0 
	bin/target6Control_writeDacReg $ASICno 61   900 
	bin/target6Control_writeDacReg $ASICno 62   1100 
	bin/target6Control_writeDacReg $ASICno 63   1100 
	bin/target6Control_writeDacReg $ASICno 64   143 
	bin/target6Control_writeDacReg $ASICno 65   163 
	bin/target6Control_writeDacReg $ASICno 66   163 
	bin/target6Control_writeDacReg $ASICno 67   178 
	bin/target6Control_writeDacReg $ASICno 68   35 
	bin/target6Control_writeDacReg $ASICno 69   45 
	bin/target6Control_writeDacReg $ASICno 70   35 
	bin/target6Control_writeDacReg $ASICno 71   50 
	bin/target6Control_writeDacReg $ASICno 72   163 
	bin/target6Control_writeDacReg $ASICno 73   173 
	bin/target6Control_writeDacReg $ASICno 74   40 
	bin/target6Control_writeDacReg $ASICno 75   58 
	bin/target6Control_writeDacReg $ASICno 76   737 
	bin/target6Control_writeDacReg $ASICno 77   3112 
	bin/target6Control_writeDacReg $ASICno 78   1152 
	bin/target6Control_writeDacReg $ASICno 79   2730 

ASICno="6"
	bin/target6Control_writeDacReg $ASICno 0    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 2    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 4    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 6    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 8    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 10   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 12   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 14   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 16   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 18   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 20   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 22   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 24   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 26   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 28   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 30   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 1    985
	bin/target6Control_writeDacReg $ASICno 3    985
	bin/target6Control_writeDacReg $ASICno 5    985
	bin/target6Control_writeDacReg $ASICno 7    985
	bin/target6Control_writeDacReg $ASICno 9    985
	bin/target6Control_writeDacReg $ASICno 11   985
	bin/target6Control_writeDacReg $ASICno 13   985
	bin/target6Control_writeDacReg $ASICno 15   985
	bin/target6Control_writeDacReg $ASICno 17   985
	bin/target6Control_writeDacReg $ASICno 19   985
	bin/target6Control_writeDacReg $ASICno 21   985
	bin/target6Control_writeDacReg $ASICno 23   985
	bin/target6Control_writeDacReg $ASICno 25   985
	bin/target6Control_writeDacReg $ASICno 27   985
	bin/target6Control_writeDacReg $ASICno 29   985
	bin/target6Control_writeDacReg $ASICno 31   985
	bin/target6Control_writeDacReg $ASICno 48   1300 
	bin/target6Control_writeDacReg $ASICno 49   0 
	bin/target6Control_writeDacReg $ASICno 50   2650 
	bin/target6Control_writeDacReg $ASICno 51   1100 
	bin/target6Control_writeDacReg $ASICno 52   1500 
	bin/target6Control_writeDacReg $ASICno 53   1062 
	bin/target6Control_writeDacReg $ASICno 54   3500 
	bin/target6Control_writeDacReg $ASICno 55   0 
	bin/target6Control_writeDacReg $ASICno 56   1152 
	bin/target6Control_writeDacReg $ASICno 57   0 
	bin/target6Control_writeDacReg $ASICno 58   2235 
	bin/target6Control_writeDacReg $ASICno 59   0 
	bin/target6Control_writeDacReg $ASICno 61   900 
	bin/target6Control_writeDacReg $ASICno 62   1100 
	bin/target6Control_writeDacReg $ASICno 63   1100 
	bin/target6Control_writeDacReg $ASICno 64   143 
	bin/target6Control_writeDacReg $ASICno 65   163 
	bin/target6Control_writeDacReg $ASICno 66   163 
	bin/target6Control_writeDacReg $ASICno 67   178 
	bin/target6Control_writeDacReg $ASICno 68   35 
	bin/target6Control_writeDacReg $ASICno 69   45 
	bin/target6Control_writeDacReg $ASICno 70   35 
	bin/target6Control_writeDacReg $ASICno 71   50 
	bin/target6Control_writeDacReg $ASICno 72   163 
	bin/target6Control_writeDacReg $ASICno 73   173 
	bin/target6Control_writeDacReg $ASICno 74   40 
	bin/target6Control_writeDacReg $ASICno 75   58 
	bin/target6Control_writeDacReg $ASICno 76   737 
	bin/target6Control_writeDacReg $ASICno 77   3112 
	bin/target6Control_writeDacReg $ASICno 78   1152 
	bin/target6Control_writeDacReg $ASICno 79   2730 

ASICno="7"
	bin/target6Control_writeDacReg $ASICno 0    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 2    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 4    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 6    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 8    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 10   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 12   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 14   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 16   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 18   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 20   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 22   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 24   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 26   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 28   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 30   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 1    985
	bin/target6Control_writeDacReg $ASICno 3    985
	bin/target6Control_writeDacReg $ASICno 5    985
	bin/target6Control_writeDacReg $ASICno 7    985
	bin/target6Control_writeDacReg $ASICno 9    985
	bin/target6Control_writeDacReg $ASICno 11   985
	bin/target6Control_writeDacReg $ASICno 13   985
	bin/target6Control_writeDacReg $ASICno 15   985
	bin/target6Control_writeDacReg $ASICno 17   985
	bin/target6Control_writeDacReg $ASICno 19   985
	bin/target6Control_writeDacReg $ASICno 21   985
	bin/target6Control_writeDacReg $ASICno 23   985
	bin/target6Control_writeDacReg $ASICno 25   985
	bin/target6Control_writeDacReg $ASICno 27   985
	bin/target6Control_writeDacReg $ASICno 29   985
	bin/target6Control_writeDacReg $ASICno 31   985
	bin/target6Control_writeDacReg $ASICno 48   1300 
	bin/target6Control_writeDacReg $ASICno 49   0 
	bin/target6Control_writeDacReg $ASICno 50   2650 
	bin/target6Control_writeDacReg $ASICno 51   1100 
	bin/target6Control_writeDacReg $ASICno 52   1500 
	bin/target6Control_writeDacReg $ASICno 53   1062 
	bin/target6Control_writeDacReg $ASICno 54   3500 
	bin/target6Control_writeDacReg $ASICno 55   0 
	bin/target6Control_writeDacReg $ASICno 56   1152 
	bin/target6Control_writeDacReg $ASICno 57   0 
	bin/target6Control_writeDacReg $ASICno 58   2235 
	bin/target6Control_writeDacReg $ASICno 59   0 
	bin/target6Control_writeDacReg $ASICno 61   900 
	bin/target6Control_writeDacReg $ASICno 62   1100 
	bin/target6Control_writeDacReg $ASICno 63   1100 
	bin/target6Control_writeDacReg $ASICno 64   143 
	bin/target6Control_writeDacReg $ASICno 65   163 
	bin/target6Control_writeDacReg $ASICno 66   163 
	bin/target6Control_writeDacReg $ASICno 67   178 
	bin/target6Control_writeDacReg $ASICno 68   35 
	bin/target6Control_writeDacReg $ASICno 69   45 
	bin/target6Control_writeDacReg $ASICno 70   35 
	bin/target6Control_writeDacReg $ASICno 71   50 
	bin/target6Control_writeDacReg $ASICno 72   163 
	bin/target6Control_writeDacReg $ASICno 73   173 
	bin/target6Control_writeDacReg $ASICno 74   40 
	bin/target6Control_writeDacReg $ASICno 75   58 
	bin/target6Control_writeDacReg $ASICno 76   737 
	bin/target6Control_writeDacReg $ASICno 77   3112 
	bin/target6Control_writeDacReg $ASICno 78   1152 
	bin/target6Control_writeDacReg $ASICno 79   2730 

ASICno="8"
	bin/target6Control_writeDacReg $ASICno 0    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 2    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 4    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 6    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 8    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 10   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 12   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 14   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 16   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 18   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 20   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 22   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 24   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 26   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 28   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 30   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 1    985
	bin/target6Control_writeDacReg $ASICno 3    985
	bin/target6Control_writeDacReg $ASICno 5    985
	bin/target6Control_writeDacReg $ASICno 7    985
	bin/target6Control_writeDacReg $ASICno 9    985
	bin/target6Control_writeDacReg $ASICno 11   985
	bin/target6Control_writeDacReg $ASICno 13   985
	bin/target6Control_writeDacReg $ASICno 15   985
	bin/target6Control_writeDacReg $ASICno 17   985
	bin/target6Control_writeDacReg $ASICno 19   985
	bin/target6Control_writeDacReg $ASICno 21   985
	bin/target6Control_writeDacReg $ASICno 23   985
	bin/target6Control_writeDacReg $ASICno 25   985
	bin/target6Control_writeDacReg $ASICno 27   985
	bin/target6Control_writeDacReg $ASICno 29   985
	bin/target6Control_writeDacReg $ASICno 31   985
	bin/target6Control_writeDacReg $ASICno 48   1300 
	bin/target6Control_writeDacReg $ASICno 49   0 
	bin/target6Control_writeDacReg $ASICno 50   2650 
	bin/target6Control_writeDacReg $ASICno 51   1100 
	bin/target6Control_writeDacReg $ASICno 52   1500 
	bin/target6Control_writeDacReg $ASICno 53   1062 
	bin/target6Control_writeDacReg $ASICno 54   3500 
	bin/target6Control_writeDacReg $ASICno 55   0 
	bin/target6Control_writeDacReg $ASICno 56   1152 
	bin/target6Control_writeDacReg $ASICno 57   0 
	bin/target6Control_writeDacReg $ASICno 58   2235 
	bin/target6Control_writeDacReg $ASICno 59   0 
	bin/target6Control_writeDacReg $ASICno 61   900 
	bin/target6Control_writeDacReg $ASICno 62   1100 
	bin/target6Control_writeDacReg $ASICno 63   1100 
	bin/target6Control_writeDacReg $ASICno 64   143 
	bin/target6Control_writeDacReg $ASICno 65   163 
	bin/target6Control_writeDacReg $ASICno 66   163 
	bin/target6Control_writeDacReg $ASICno 67   178 
	bin/target6Control_writeDacReg $ASICno 68   35 
	bin/target6Control_writeDacReg $ASICno 69   45 
	bin/target6Control_writeDacReg $ASICno 70   35 
	bin/target6Control_writeDacReg $ASICno 71   50 
	bin/target6Control_writeDacReg $ASICno 72   163 
	bin/target6Control_writeDacReg $ASICno 73   173 
	bin/target6Control_writeDacReg $ASICno 74   40 
	bin/target6Control_writeDacReg $ASICno 75   58 
	bin/target6Control_writeDacReg $ASICno 76   737 
	bin/target6Control_writeDacReg $ASICno 77   3112 
	bin/target6Control_writeDacReg $ASICno 78   1152 
	bin/target6Control_writeDacReg $ASICno 79   2730 

ASICno="9"
	bin/target6Control_writeDacReg $ASICno 0    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 2    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 4    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 6    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 8    $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 10   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 12   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 14   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 16   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 18   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 20   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 22   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 24   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 26   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 28   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 30   $TrigThreshold
	bin/target6Control_writeDacReg $ASICno 1    985
	bin/target6Control_writeDacReg $ASICno 3    985
	bin/target6Control_writeDacReg $ASICno 5    985
	bin/target6Control_writeDacReg $ASICno 7    985
	bin/target6Control_writeDacReg $ASICno 9    985
	bin/target6Control_writeDacReg $ASICno 11   985
	bin/target6Control_writeDacReg $ASICno 13   985
	bin/target6Control_writeDacReg $ASICno 15   985
	bin/target6Control_writeDacReg $ASICno 17   985
	bin/target6Control_writeDacReg $ASICno 19   985
	bin/target6Control_writeDacReg $ASICno 21   985
	bin/target6Control_writeDacReg $ASICno 23   985
	bin/target6Control_writeDacReg $ASICno 25   985
	bin/target6Control_writeDacReg $ASICno 27   985
	bin/target6Control_writeDacReg $ASICno 29   985
	bin/target6Control_writeDacReg $ASICno 31   985
	bin/target6Control_writeDacReg $ASICno 48   1300 
	bin/target6Control_writeDacReg $ASICno 49   0 
	bin/target6Control_writeDacReg $ASICno 50   2650 
	bin/target6Control_writeDacReg $ASICno 51   1100 
	bin/target6Control_writeDacReg $ASICno 52   1500 
	bin/target6Control_writeDacReg $ASICno 53   1062 
	bin/target6Control_writeDacReg $ASICno 54   3500 
	bin/target6Control_writeDacReg $ASICno 55   0 
	bin/target6Control_writeDacReg $ASICno 56   1152 
	bin/target6Control_writeDacReg $ASICno 57   0 
	bin/target6Control_writeDacReg $ASICno 58   2235 
	bin/target6Control_writeDacReg $ASICno 59   0 
	bin/target6Control_writeDacReg $ASICno 61   900 
	bin/target6Control_writeDacReg $ASICno 62   1100 
	bin/target6Control_writeDacReg $ASICno 63   1100 
	bin/target6Control_writeDacReg $ASICno 64   143 
	bin/target6Control_writeDacReg $ASICno 65   163 
	bin/target6Control_writeDacReg $ASICno 66   163 
	bin/target6Control_writeDacReg $ASICno 67   178 
	bin/target6Control_writeDacReg $ASICno 68   35 
	bin/target6Control_writeDacReg $ASICno 69   45 
	bin/target6Control_writeDacReg $ASICno 70   35 
	bin/target6Control_writeDacReg $ASICno 71   50 
	bin/target6Control_writeDacReg $ASICno 72   163 
	bin/target6Control_writeDacReg $ASICno 73   173 
	bin/target6Control_writeDacReg $ASICno 74   40 
	bin/target6Control_writeDacReg $ASICno 75   58 
	bin/target6Control_writeDacReg $ASICno 76   737 
	bin/target6Control_writeDacReg $ASICno 77   3112 
	bin/target6Control_writeDacReg $ASICno 78   1152 
	bin/target6Control_writeDacReg $ASICno 79   2730 



	
