ROOTCFLAGS    = $(shell ${ROOTSYS}/bin/root-config --cflags)
ROOTLIBS      = $(shell ${ROOTSYS}/bin/root-config --libs)
ROOTGLIBS     = $(shell ${ROOTSYS}/bin/root-config --glibs)

CXX           = g++
CXXFLAGS      = -g -Wall -fPIC -std=c++0x
LD            = g++
LDFLAGS       = -g -std=c++0x
SOFLAGS       = -shared

CXXFLAGS      += $(ROOTCFLAGS)
LIBS           = $(ROOTLIBS) 
NGLIBS         = $(ROOTGLIBS) 
NGLIBS        += -lMinuit
GLIBS          = $(filter-out -lNew, $(NGLIBS))

.SUFFIXES: .cc,.C


# ================================================================================
GetMeanAndRMSFromIRS3BCopperTriggerData:  GetMeanAndRMSFromIRS3BCopperTriggerData.o
# -------------------------

	$(LD) $(LDFLAGS)  -o GetMeanAndRMSFromIRS3BCopperTriggerData GetMeanAndRMSFromIRS3BCopperTriggerData.o $(GLIBS)
.cc.o:
	$(CXX) $(CXXFLAGS) -c $<
clean:
	rm -f core GetMeanAndRMSFromIRS3BCopperTriggerData GetMeanAndRMSFromIRS3BCopperTriggerData.o 
