#ChipScope Core Inserter Project File Version 3.0
#Tue Apr 07 17:06:36 HST 2015
Project.device.designInputFile=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\scrod_top_A4.ngc
Project.device.designOutputFile=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\scrod_top_A4_csp.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\_ngo2
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=enOutput
Project.filter<11>=internal_adc*
Project.filter<12>=interna;_adc*
Project.filter<13>=internal_CL*
Project.filter<14>=internal_MP*
Project.filter<15>=internal_CLOCK*
Project.filter<16>=trg*
Project.filter<17>=ctime*
Project.filter<18>=internal_TRIGGER_ASIC*
Project.filter<1>=internal_DAC_*
Project.filter<2>=internal_DAC_PATGEN*
Project.filter<3>=internal_DAC_PATGEN_ADDR*
Project.filter<4>=internal*
Project.filter<5>=LEDS*
Project.filter<6>=LEDS(0)
Project.filter<7>=internal_CurrentADC_reset
Project.filter<8>=internal_MCP_ADC_counter
Project.filter<9>=internal_enOutput
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface FIFO_CLOCK
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=8
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_WRITE_ENABLE
Project.unit<0>.triggerChannel<0><1>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_WRITE_ENABLE
Project.unit<0>.triggerChannel<0><2>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_READ_ENABLE
Project.unit<0>.triggerChannel<0><3>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_READ_ENABLE
Project.unit<0>.triggerChannel<0><4>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_flagA_in
Project.unit<0>.triggerChannel<0><5>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_flagB_in
Project.unit<0>.triggerChannel<0><6>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_FULL
Project.unit<0>.triggerChannel<0><7>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_FULL
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
