#ChipScope Core Inserter Project File Version 3.0
#Fri Apr 03 13:25:50 HST 2015
Project.device.designInputFile=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\scrod_top_A4.ngc
Project.device.designOutputFile=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\scrod_top_A4_csp.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\_ngo2
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=internal_DAC_*
Project.filter<10>=enOutput
Project.filter<11>=internal_adc*
Project.filter<12>=interna;_adc*
Project.filter<13>=internal_CL*
Project.filter<14>=internal_MP*
Project.filter<15>=internal_CLOCK*
Project.filter<16>=trg*
Project.filter<17>=ctime*
Project.filter<18>=internal_TRIGGER_ASIC*
Project.filter<1>=internal_DAC_PATGEN*
Project.filter<2>=internal_DAC_PATGEN_ADDR*
Project.filter<3>=internal*
Project.filter<4>=
Project.filter<5>=LEDS*
Project.filter<6>=LEDS(0)
Project.filter<7>=internal_CurrentADC_reset
Project.filter<8>=internal_MCP_ADC_counter
Project.filter<9>=internal_enOutput
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=inst_mcp_adc clkCounter<12>
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=inst_mcp_adc runADC
Project.unit<0>.dataChannel<10>=internal_ADCOutput<2>
Project.unit<0>.dataChannel<11>=internal_ADCOutput<1>
Project.unit<0>.dataChannel<12>=internal_ADCOutput<0>
Project.unit<0>.dataChannel<13>=COUNTER_LOAD_MACRO_inst Q<15>
Project.unit<0>.dataChannel<14>=COUNTER_LOAD_MACRO_inst Q<14>
Project.unit<0>.dataChannel<15>=COUNTER_LOAD_MACRO_inst Q<13>
Project.unit<0>.dataChannel<16>=COUNTER_LOAD_MACRO_inst Q<12>
Project.unit<0>.dataChannel<17>=COUNTER_LOAD_MACRO_inst Q<11>
Project.unit<0>.dataChannel<18>=COUNTER_LOAD_MACRO_inst Q<10>
Project.unit<0>.dataChannel<19>=COUNTER_LOAD_MACRO_inst Q<9>
Project.unit<0>.dataChannel<1>=internal_ADCOutput<11>
Project.unit<0>.dataChannel<20>=COUNTER_LOAD_MACRO_inst Q<8>
Project.unit<0>.dataChannel<21>=COUNTER_LOAD_MACRO_inst Q<7>
Project.unit<0>.dataChannel<22>=COUNTER_LOAD_MACRO_inst Q<6>
Project.unit<0>.dataChannel<23>=COUNTER_LOAD_MACRO_inst Q<5>
Project.unit<0>.dataChannel<24>=COUNTER_LOAD_MACRO_inst Q<4>
Project.unit<0>.dataChannel<25>=COUNTER_LOAD_MACRO_inst Q<3>
Project.unit<0>.dataChannel<26>=COUNTER_LOAD_MACRO_inst Q<2>
Project.unit<0>.dataChannel<27>=COUNTER_LOAD_MACRO_inst Q<1>
Project.unit<0>.dataChannel<28>=COUNTER_LOAD_MACRO_inst Q<0>
Project.unit<0>.dataChannel<29>=LEDS_11_OBUF
Project.unit<0>.dataChannel<2>=internal_ADCOutput<10>
Project.unit<0>.dataChannel<30>=inst_mcp_adc idxBit<2>
Project.unit<0>.dataChannel<31>=inst_mcp_adc idxBit<1>
Project.unit<0>.dataChannel<32>=inst_mcp_adc idxBit<0>
Project.unit<0>.dataChannel<33>=inst_mcp_adc idxBit<3>
Project.unit<0>.dataChannel<34>=inst_mcp_adc readyForNextState
Project.unit<0>.dataChannel<35>=internal_DAC_PATGEN_ADDR<3>
Project.unit<0>.dataChannel<36>=internal_DAC_PATGEN_ADDR<2>
Project.unit<0>.dataChannel<37>=internal_DAC_PATGEN_ADDR<1>
Project.unit<0>.dataChannel<38>=internal_DAC_PATGEN_ADDR<0>
Project.unit<0>.dataChannel<39>=internal_DAC_PATGEN_VAL<7>
Project.unit<0>.dataChannel<3>=internal_ADCOutput<9>
Project.unit<0>.dataChannel<40>=internal_DAC_PATGEN_VAL<6>
Project.unit<0>.dataChannel<41>=internal_DAC_PATGEN_VAL<5>
Project.unit<0>.dataChannel<42>=internal_DAC_PATGEN_VAL<4>
Project.unit<0>.dataChannel<43>=internal_DAC_PATGEN_VAL<3>
Project.unit<0>.dataChannel<44>=internal_DAC_PATGEN_VAL<2>
Project.unit<0>.dataChannel<45>=internal_DAC_PATGEN_VAL<1>
Project.unit<0>.dataChannel<46>=internal_DAC_PATGEN_VAL<0>
Project.unit<0>.dataChannel<47>=internal_DAC_PATGEN_UPDATE
Project.unit<0>.dataChannel<48>=internal_DAC_CONTROL_busy
Project.unit<0>.dataChannel<49>=inst_mcp_adc scl
Project.unit<0>.dataChannel<4>=internal_ADCOutput<8>
Project.unit<0>.dataChannel<50>=inst_mcp_adc dataToRead<6>
Project.unit<0>.dataChannel<51>=inst_mcp_adc dataToRead<5>
Project.unit<0>.dataChannel<52>=inst_mcp_adc dataToRead<4>
Project.unit<0>.dataChannel<53>=inst_mcp_adc dataToRead<3>
Project.unit<0>.dataChannel<54>=inst_mcp_adc dataToRead<2>
Project.unit<0>.dataChannel<55>=inst_mcp_adc dataToRead<1>
Project.unit<0>.dataChannel<56>=inst_mcp_adc dataToRead<0>
Project.unit<0>.dataChannel<57>=inst_mcp_adc idxCyc<1>
Project.unit<0>.dataChannel<58>=inst_mcp_adc Result<0>
Project.unit<0>.dataChannel<59>=COUNTER_LOAD_MACRO_inst Q<26>
Project.unit<0>.dataChannel<5>=internal_ADCOutput<7>
Project.unit<0>.dataChannel<6>=internal_ADCOutput<6>
Project.unit<0>.dataChannel<7>=internal_ADCOutput<5>
Project.unit<0>.dataChannel<8>=internal_ADCOutput<4>
Project.unit<0>.dataChannel<9>=internal_ADCOutput<3>
Project.unit<0>.dataDepth=8192
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=60
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=inst_mcp_adc runADC
Project.unit<0>.triggerChannel<0><1>=inst_mcp_adc i_runADC
Project.unit<0>.triggerChannel<0><2>=inst_mpps_dacs WRITE_STROBE
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=3
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
