#ChipScope Core Inserter Project File Version 3.0
#Thu Apr 09 13:21:15 HST 2015
Project.device.designInputFile=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\scrod_top_A4.ngc
Project.device.designOutputFile=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\scrod_top_A4_csp.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\_ngo2
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=internal_enOutput
Project.filter<11>=enOutput
Project.filter<12>=internal_adc*
Project.filter<13>=interna;_adc*
Project.filter<14>=internal_CL*
Project.filter<15>=internal_MP*
Project.filter<16>=internal_CLOCK*
Project.filter<17>=trg*
Project.filter<18>=ctime*
Project.filter<1>=internal_clock*
Project.filter<2>=internal_DAC_*
Project.filter<3>=internal_DAC_PATGEN*
Project.filter<4>=internal_DAC_PATGEN_ADDR*
Project.filter<5>=internal*
Project.filter<6>=LEDS*
Project.filter<7>=LEDS(0)
Project.filter<8>=internal_CurrentADC_reset
Project.filter<9>=internal_MCP_ADC_counter
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=2
Project.unit<0>.clockChannel=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface FIFO_CLOCK
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_WRITE_ENABLE
Project.unit<0>.dataChannel<1>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_WRITE_ENABLE
Project.unit<0>.dataChannel<2>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_READ_ENABLE
Project.unit<0>.dataChannel<3>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_READ_ENABLE
Project.unit<0>.dataChannel<4>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_flagA_in
Project.unit<0>.dataChannel<5>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_flagB_in
Project.unit<0>.dataChannel<6>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_FULL
Project.unit<0>.dataChannel<7>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_FULL
Project.unit<0>.dataDepth=4096
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=88
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_WRITE_ENABLE
Project.unit<0>.triggerChannel<0><1>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_WRITE_ENABLE
Project.unit<0>.triggerChannel<0><2>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_READ_ENABLE
Project.unit<0>.triggerChannel<0><3>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_READ_ENABLE
Project.unit<0>.triggerChannel<0><4>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_flagA_in
Project.unit<0>.triggerChannel<0><5>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_flagB_in
Project.unit<0>.triggerChannel<0><6>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_FULL
Project.unit<0>.triggerChannel<0><7>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_FULL
Project.unit<0>.triggerChannel<1><0>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<15>
Project.unit<0>.triggerChannel<1><10>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<5>
Project.unit<0>.triggerChannel<1><11>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<4>
Project.unit<0>.triggerChannel<1><12>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<3>
Project.unit<0>.triggerChannel<1><13>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<2>
Project.unit<0>.triggerChannel<1><14>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<1>
Project.unit<0>.triggerChannel<1><15>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<0>
Project.unit<0>.triggerChannel<1><16>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<15>
Project.unit<0>.triggerChannel<1><17>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<14>
Project.unit<0>.triggerChannel<1><18>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<13>
Project.unit<0>.triggerChannel<1><19>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<12>
Project.unit<0>.triggerChannel<1><1>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<14>
Project.unit<0>.triggerChannel<1><20>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<11>
Project.unit<0>.triggerChannel<1><21>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<10>
Project.unit<0>.triggerChannel<1><22>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<9>
Project.unit<0>.triggerChannel<1><23>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<8>
Project.unit<0>.triggerChannel<1><24>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<7>
Project.unit<0>.triggerChannel<1><25>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<6>
Project.unit<0>.triggerChannel<1><26>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<5>
Project.unit<0>.triggerChannel<1><27>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<4>
Project.unit<0>.triggerChannel<1><28>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<3>
Project.unit<0>.triggerChannel<1><29>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<2>
Project.unit<0>.triggerChannel<1><2>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<13>
Project.unit<0>.triggerChannel<1><30>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<1>
Project.unit<0>.triggerChannel<1><31>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_DATA<0>
Project.unit<0>.triggerChannel<1><32>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<15>
Project.unit<0>.triggerChannel<1><33>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<14>
Project.unit<0>.triggerChannel<1><34>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<13>
Project.unit<0>.triggerChannel<1><35>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<12>
Project.unit<0>.triggerChannel<1><36>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<11>
Project.unit<0>.triggerChannel<1><37>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<10>
Project.unit<0>.triggerChannel<1><38>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<9>
Project.unit<0>.triggerChannel<1><39>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<8>
Project.unit<0>.triggerChannel<1><3>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<12>
Project.unit<0>.triggerChannel<1><40>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<7>
Project.unit<0>.triggerChannel<1><41>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<6>
Project.unit<0>.triggerChannel<1><42>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<5>
Project.unit<0>.triggerChannel<1><43>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<4>
Project.unit<0>.triggerChannel<1><44>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<3>
Project.unit<0>.triggerChannel<1><45>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<2>
Project.unit<0>.triggerChannel<1><46>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<1>
Project.unit<0>.triggerChannel<1><47>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<0>
Project.unit<0>.triggerChannel<1><48>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<15>
Project.unit<0>.triggerChannel<1><49>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<14>
Project.unit<0>.triggerChannel<1><4>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<11>
Project.unit<0>.triggerChannel<1><50>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<13>
Project.unit<0>.triggerChannel<1><51>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<12>
Project.unit<0>.triggerChannel<1><52>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<11>
Project.unit<0>.triggerChannel<1><53>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<10>
Project.unit<0>.triggerChannel<1><54>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<9>
Project.unit<0>.triggerChannel<1><55>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<8>
Project.unit<0>.triggerChannel<1><56>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<7>
Project.unit<0>.triggerChannel<1><57>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<6>
Project.unit<0>.triggerChannel<1><58>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<5>
Project.unit<0>.triggerChannel<1><59>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<4>
Project.unit<0>.triggerChannel<1><5>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<10>
Project.unit<0>.triggerChannel<1><60>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<3>
Project.unit<0>.triggerChannel<1><61>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<2>
Project.unit<0>.triggerChannel<1><62>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<1>
Project.unit<0>.triggerChannel<1><63>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_DATA<0>
Project.unit<0>.triggerChannel<1><64>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<15>
Project.unit<0>.triggerChannel<1><65>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<14>
Project.unit<0>.triggerChannel<1><66>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<13>
Project.unit<0>.triggerChannel<1><67>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<12>
Project.unit<0>.triggerChannel<1><68>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<11>
Project.unit<0>.triggerChannel<1><69>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<10>
Project.unit<0>.triggerChannel<1><6>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<9>
Project.unit<0>.triggerChannel<1><70>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<9>
Project.unit<0>.triggerChannel<1><71>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<8>
Project.unit<0>.triggerChannel<1><72>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<7>
Project.unit<0>.triggerChannel<1><73>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<6>
Project.unit<0>.triggerChannel<1><74>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<5>
Project.unit<0>.triggerChannel<1><75>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<4>
Project.unit<0>.triggerChannel<1><76>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<3>
Project.unit<0>.triggerChannel<1><77>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<2>
Project.unit<0>.triggerChannel<1><78>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<1>
Project.unit<0>.triggerChannel<1><79>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_DATA<0>
Project.unit<0>.triggerChannel<1><7>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<8>
Project.unit<0>.triggerChannel<1><8>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<7>
Project.unit<0>.triggerChannel<1><9>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_DATA<6>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerPortCount=2
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerPortWidth<1>=80
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
Project.unit<1>.clockChannel=internal_CLOCK_FPGA_LOGIC
Project.unit<1>.clockEdge=Rising
Project.unit<1>.dataDepth=1024
Project.unit<1>.dataEqualsTrigger=true
Project.unit<1>.dataPortWidth=190
Project.unit<1>.enableGaps=false
Project.unit<1>.enableStorageQualification=true
Project.unit<1>.enableTimestamps=false
Project.unit<1>.timestampDepth=0
Project.unit<1>.timestampWidth=0
Project.unit<1>.triggerChannel<0><0>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<31>
Project.unit<1>.triggerChannel<0><100>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<5>
Project.unit<1>.triggerChannel<0><101>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<4>
Project.unit<1>.triggerChannel<0><102>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<3>
Project.unit<1>.triggerChannel<0><103>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<2>
Project.unit<1>.triggerChannel<0><104>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<1>
Project.unit<1>.triggerChannel<0><105>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<0>
Project.unit<1>.triggerChannel<0><106>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_EMPTY
Project.unit<1>.triggerChannel<0><107>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_VALID
Project.unit<1>.triggerChannel<0><108>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<31>
Project.unit<1>.triggerChannel<0><109>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<30>
Project.unit<1>.triggerChannel<0><10>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<21>
Project.unit<1>.triggerChannel<0><110>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<29>
Project.unit<1>.triggerChannel<0><111>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<28>
Project.unit<1>.triggerChannel<0><112>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<27>
Project.unit<1>.triggerChannel<0><113>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<26>
Project.unit<1>.triggerChannel<0><114>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<25>
Project.unit<1>.triggerChannel<0><115>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<24>
Project.unit<1>.triggerChannel<0><116>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<23>
Project.unit<1>.triggerChannel<0><117>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<22>
Project.unit<1>.triggerChannel<0><118>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<21>
Project.unit<1>.triggerChannel<0><119>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<20>
Project.unit<1>.triggerChannel<0><11>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<20>
Project.unit<1>.triggerChannel<0><120>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<19>
Project.unit<1>.triggerChannel<0><121>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<18>
Project.unit<1>.triggerChannel<0><122>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<17>
Project.unit<1>.triggerChannel<0><123>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<16>
Project.unit<1>.triggerChannel<0><124>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<15>
Project.unit<1>.triggerChannel<0><125>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<14>
Project.unit<1>.triggerChannel<0><126>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<13>
Project.unit<1>.triggerChannel<0><127>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<12>
Project.unit<1>.triggerChannel<0><128>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<11>
Project.unit<1>.triggerChannel<0><129>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<10>
Project.unit<1>.triggerChannel<0><12>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<19>
Project.unit<1>.triggerChannel<0><130>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<9>
Project.unit<1>.triggerChannel<0><131>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<8>
Project.unit<1>.triggerChannel<0><132>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<7>
Project.unit<1>.triggerChannel<0><133>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<6>
Project.unit<1>.triggerChannel<0><134>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<5>
Project.unit<1>.triggerChannel<0><135>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<4>
Project.unit<1>.triggerChannel<0><136>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<3>
Project.unit<1>.triggerChannel<0><137>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<2>
Project.unit<1>.triggerChannel<0><138>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<1>
Project.unit<1>.triggerChannel<0><139>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_DATA<0>
Project.unit<1>.triggerChannel<0><13>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<18>
Project.unit<1>.triggerChannel<0><140>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_EMPTY
Project.unit<1>.triggerChannel<0><141>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_VALID
Project.unit<1>.triggerChannel<0><142>=map_readout_interfaces map_daq_fifo_layer internal_USB_RX_0_VALID
Project.unit<1>.triggerChannel<0><143>=map_readout_interfaces map_daq_fifo_layer internal_FIFO_OUT_0_READ_ENABLE
Project.unit<1>.triggerChannel<0><144>=map_readout_interfaces map_daq_fifo_layer internal_FIFO_OUT_1_READ_ENABLE
Project.unit<1>.triggerChannel<0><145>=map_readout_interfaces map_daq_fifo_layer internal_FIFO_INP_0_WRITE_ENABLE
Project.unit<1>.triggerChannel<0><146>=map_readout_interfaces map_daq_fifo_layer internal_FIFO_INP_1_WRITE_ENABLE
Project.unit<1>.triggerChannel<0><147>=map_readout_interfaces map_daq_fifo_layer internal_FIFO_INP_1_FULL
Project.unit<1>.triggerChannel<0><148>=
Project.unit<1>.triggerChannel<0><149>=
Project.unit<1>.triggerChannel<0><14>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<17>
Project.unit<1>.triggerChannel<0><150>=
Project.unit<1>.triggerChannel<0><151>=
Project.unit<1>.triggerChannel<0><152>=
Project.unit<1>.triggerChannel<0><153>=
Project.unit<1>.triggerChannel<0><154>=
Project.unit<1>.triggerChannel<0><155>=
Project.unit<1>.triggerChannel<0><156>=
Project.unit<1>.triggerChannel<0><157>=
Project.unit<1>.triggerChannel<0><158>=
Project.unit<1>.triggerChannel<0><159>=
Project.unit<1>.triggerChannel<0><15>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<16>
Project.unit<1>.triggerChannel<0><160>=
Project.unit<1>.triggerChannel<0><161>=
Project.unit<1>.triggerChannel<0><162>=
Project.unit<1>.triggerChannel<0><163>=
Project.unit<1>.triggerChannel<0><164>=
Project.unit<1>.triggerChannel<0><165>=
Project.unit<1>.triggerChannel<0><166>=
Project.unit<1>.triggerChannel<0><167>=
Project.unit<1>.triggerChannel<0><168>=
Project.unit<1>.triggerChannel<0><169>=
Project.unit<1>.triggerChannel<0><16>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<15>
Project.unit<1>.triggerChannel<0><170>=
Project.unit<1>.triggerChannel<0><171>=
Project.unit<1>.triggerChannel<0><172>=
Project.unit<1>.triggerChannel<0><173>=
Project.unit<1>.triggerChannel<0><174>=
Project.unit<1>.triggerChannel<0><175>=
Project.unit<1>.triggerChannel<0><176>=
Project.unit<1>.triggerChannel<0><177>=
Project.unit<1>.triggerChannel<0><178>=
Project.unit<1>.triggerChannel<0><179>=
Project.unit<1>.triggerChannel<0><17>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<14>
Project.unit<1>.triggerChannel<0><18>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<13>
Project.unit<1>.triggerChannel<0><19>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<12>
Project.unit<1>.triggerChannel<0><1>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<30>
Project.unit<1>.triggerChannel<0><20>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<11>
Project.unit<1>.triggerChannel<0><21>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<10>
Project.unit<1>.triggerChannel<0><22>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<9>
Project.unit<1>.triggerChannel<0><23>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<8>
Project.unit<1>.triggerChannel<0><24>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<7>
Project.unit<1>.triggerChannel<0><25>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<6>
Project.unit<1>.triggerChannel<0><26>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<5>
Project.unit<1>.triggerChannel<0><27>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<4>
Project.unit<1>.triggerChannel<0><28>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<3>
Project.unit<1>.triggerChannel<0><29>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<2>
Project.unit<1>.triggerChannel<0><2>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<29>
Project.unit<1>.triggerChannel<0><30>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<1>
Project.unit<1>.triggerChannel<0><31>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<0>
Project.unit<1>.triggerChannel<0><32>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<31>
Project.unit<1>.triggerChannel<0><33>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<30>
Project.unit<1>.triggerChannel<0><34>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<29>
Project.unit<1>.triggerChannel<0><35>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<28>
Project.unit<1>.triggerChannel<0><36>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<27>
Project.unit<1>.triggerChannel<0><37>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<26>
Project.unit<1>.triggerChannel<0><38>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<25>
Project.unit<1>.triggerChannel<0><39>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<24>
Project.unit<1>.triggerChannel<0><3>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<28>
Project.unit<1>.triggerChannel<0><40>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<23>
Project.unit<1>.triggerChannel<0><41>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<22>
Project.unit<1>.triggerChannel<0><42>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<21>
Project.unit<1>.triggerChannel<0><43>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<20>
Project.unit<1>.triggerChannel<0><44>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<19>
Project.unit<1>.triggerChannel<0><45>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<18>
Project.unit<1>.triggerChannel<0><46>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<17>
Project.unit<1>.triggerChannel<0><47>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<16>
Project.unit<1>.triggerChannel<0><48>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<15>
Project.unit<1>.triggerChannel<0><49>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<14>
Project.unit<1>.triggerChannel<0><4>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<27>
Project.unit<1>.triggerChannel<0><50>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<13>
Project.unit<1>.triggerChannel<0><51>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<12>
Project.unit<1>.triggerChannel<0><52>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<11>
Project.unit<1>.triggerChannel<0><53>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<10>
Project.unit<1>.triggerChannel<0><54>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<9>
Project.unit<1>.triggerChannel<0><55>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<8>
Project.unit<1>.triggerChannel<0><56>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<7>
Project.unit<1>.triggerChannel<0><57>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<6>
Project.unit<1>.triggerChannel<0><58>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<5>
Project.unit<1>.triggerChannel<0><59>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<4>
Project.unit<1>.triggerChannel<0><5>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<26>
Project.unit<1>.triggerChannel<0><60>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<3>
Project.unit<1>.triggerChannel<0><61>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<2>
Project.unit<1>.triggerChannel<0><62>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<1>
Project.unit<1>.triggerChannel<0><63>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_DATA<0>
Project.unit<1>.triggerChannel<0><64>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_WR_EN
Project.unit<1>.triggerChannel<0><65>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_RD_EN
Project.unit<1>.triggerChannel<0><66>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_WR_EN
Project.unit<1>.triggerChannel<0><67>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_1_RD_EN
Project.unit<1>.triggerChannel<0><68>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_FULL
Project.unit<1>.triggerChannel<0><69>=map_readout_interfaces map_daq_fifo_layer internal_FIFO_OUT_0_EMPTY
Project.unit<1>.triggerChannel<0><6>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<25>
Project.unit<1>.triggerChannel<0><70>=map_readout_interfaces map_daq_fifo_layer internal_FIFO_OUT_0_VALID
Project.unit<1>.triggerChannel<0><71>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_1_FULL
Project.unit<1>.triggerChannel<0><72>=map_readout_interfaces map_daq_fifo_layer internal_FIFO_OUT_1_EMPTY
Project.unit<1>.triggerChannel<0><73>=map_readout_interfaces map_daq_fifo_layer internal_FIFO_OUT_1_VALID
Project.unit<1>.triggerChannel<0><74>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<31>
Project.unit<1>.triggerChannel<0><75>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<30>
Project.unit<1>.triggerChannel<0><76>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<29>
Project.unit<1>.triggerChannel<0><77>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<28>
Project.unit<1>.triggerChannel<0><78>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<27>
Project.unit<1>.triggerChannel<0><79>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<26>
Project.unit<1>.triggerChannel<0><7>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<24>
Project.unit<1>.triggerChannel<0><80>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<25>
Project.unit<1>.triggerChannel<0><81>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<24>
Project.unit<1>.triggerChannel<0><82>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<23>
Project.unit<1>.triggerChannel<0><83>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<22>
Project.unit<1>.triggerChannel<0><84>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<21>
Project.unit<1>.triggerChannel<0><85>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<20>
Project.unit<1>.triggerChannel<0><86>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<19>
Project.unit<1>.triggerChannel<0><87>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<18>
Project.unit<1>.triggerChannel<0><88>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<17>
Project.unit<1>.triggerChannel<0><89>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<16>
Project.unit<1>.triggerChannel<0><8>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<23>
Project.unit<1>.triggerChannel<0><90>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<15>
Project.unit<1>.triggerChannel<0><91>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<14>
Project.unit<1>.triggerChannel<0><92>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<13>
Project.unit<1>.triggerChannel<0><93>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<12>
Project.unit<1>.triggerChannel<0><94>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<11>
Project.unit<1>.triggerChannel<0><95>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<10>
Project.unit<1>.triggerChannel<0><96>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<9>
Project.unit<1>.triggerChannel<0><97>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<8>
Project.unit<1>.triggerChannel<0><98>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<7>
Project.unit<1>.triggerChannel<0><99>=map_readout_interfaces map_daq_fifo_layer FIFO_INP_0_DATA<6>
Project.unit<1>.triggerChannel<0><9>=map_readout_interfaces map_daq_fifo_layer FIFO_OUT_0_DATA<22>
Project.unit<1>.triggerChannel<1><0>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<15>
Project.unit<1>.triggerChannel<1><10>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<5>
Project.unit<1>.triggerChannel<1><11>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<4>
Project.unit<1>.triggerChannel<1><12>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<3>
Project.unit<1>.triggerChannel<1><13>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<2>
Project.unit<1>.triggerChannel<1><14>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<1>
Project.unit<1>.triggerChannel<1><15>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<0>
Project.unit<1>.triggerChannel<1><16>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_flagA_in
Project.unit<1>.triggerChannel<1><17>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_flagB_in
Project.unit<1>.triggerChannel<1><18>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface rst_usb_clk
Project.unit<1>.triggerChannel<1><19>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_wakeup_in
Project.unit<1>.triggerChannel<1><1>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<14>
Project.unit<1>.triggerChannel<1><20>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_slrd
Project.unit<1>.triggerChannel<1><21>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_slwr
Project.unit<1>.triggerChannel<1><22>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_pktend
Project.unit<1>.triggerChannel<1><23>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_sloe
Project.unit<1>.triggerChannel<1><24>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<15>
Project.unit<1>.triggerChannel<1><25>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<14>
Project.unit<1>.triggerChannel<1><26>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<13>
Project.unit<1>.triggerChannel<1><27>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<12>
Project.unit<1>.triggerChannel<1><28>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<11>
Project.unit<1>.triggerChannel<1><29>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<10>
Project.unit<1>.triggerChannel<1><2>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<13>
Project.unit<1>.triggerChannel<1><30>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<9>
Project.unit<1>.triggerChannel<1><31>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<8>
Project.unit<1>.triggerChannel<1><32>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<7>
Project.unit<1>.triggerChannel<1><33>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<6>
Project.unit<1>.triggerChannel<1><34>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<5>
Project.unit<1>.triggerChannel<1><35>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<4>
Project.unit<1>.triggerChannel<1><36>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<3>
Project.unit<1>.triggerChannel<1><37>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<2>
Project.unit<1>.triggerChannel<1><38>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<1>
Project.unit<1>.triggerChannel<1><39>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_out<0>
Project.unit<1>.triggerChannel<1><3>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<12>
Project.unit<1>.triggerChannel<1><40>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fifo_adr<1>
Project.unit<1>.triggerChannel<1><41>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fifo_adr<0>
Project.unit<1>.triggerChannel<1><42>=
Project.unit<1>.triggerChannel<1><43>=
Project.unit<1>.triggerChannel<1><44>=
Project.unit<1>.triggerChannel<1><45>=
Project.unit<1>.triggerChannel<1><46>=
Project.unit<1>.triggerChannel<1><47>=
Project.unit<1>.triggerChannel<1><48>=
Project.unit<1>.triggerChannel<1><49>=
Project.unit<1>.triggerChannel<1><4>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<11>
Project.unit<1>.triggerChannel<1><5>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<10>
Project.unit<1>.triggerChannel<1><6>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<9>
Project.unit<1>.triggerChannel<1><7>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<8>
Project.unit<1>.triggerChannel<1><8>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<7>
Project.unit<1>.triggerChannel<1><9>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_fd_in<6>
Project.unit<1>.triggerConditionCountWidth=0
Project.unit<1>.triggerMatchCount<0>=1
Project.unit<1>.triggerMatchCount<1>=1
Project.unit<1>.triggerMatchCountWidth<0><0>=0
Project.unit<1>.triggerMatchCountWidth<1><0>=0
Project.unit<1>.triggerMatchType<0><0>=1
Project.unit<1>.triggerMatchType<1><0>=1
Project.unit<1>.triggerPortCount=2
Project.unit<1>.triggerPortIsData<0>=true
Project.unit<1>.triggerPortIsData<1>=true
Project.unit<1>.triggerPortWidth<0>=148
Project.unit<1>.triggerPortWidth<1>=42
Project.unit<1>.triggerSequencerLevels=16
Project.unit<1>.triggerSequencerType=1
Project.unit<1>.type=ilapro
