#ChipScope Core Inserter Project File Version 3.0
#Tue Apr 07 10:18:07 HST 2015
Project.device.designInputFile=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\scrod_top_A4.ngc
Project.device.designOutputFile=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\scrod_top_A4_csp.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\Users\\isar\\Documents\\code5\\TX9UMB-4\\ise-project\\_ngo2
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=enOutput
Project.filter<11>=internal_adc*
Project.filter<12>=interna;_adc*
Project.filter<13>=internal_CL*
Project.filter<14>=internal_MP*
Project.filter<15>=internal_CLOCK*
Project.filter<16>=trg*
Project.filter<17>=ctime*
Project.filter<18>=internal_TRIGGER_ASIC*
Project.filter<1>=internal_DAC_*
Project.filter<2>=internal_DAC_PATGEN*
Project.filter<3>=internal_DAC_PATGEN_ADDR*
Project.filter<4>=internal*
Project.filter<5>=LEDS*
Project.filter<6>=LEDS(0)
Project.filter<7>=internal_CurrentADC_reset
Project.filter<8>=internal_MCP_ADC_counter
Project.filter<9>=internal_enOutput
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=2
Project.unit<0>.clockChannel=inst_mcp_adc clkCounter<12>
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=inst_mcp_adc runADC
Project.unit<0>.dataChannel<10>=internal_ADCOutput<2>
Project.unit<0>.dataChannel<11>=internal_ADCOutput<1>
Project.unit<0>.dataChannel<12>=internal_ADCOutput<0>
Project.unit<0>.dataChannel<13>=LEDS_11_OBUF
Project.unit<0>.dataChannel<14>=inst_mcp_adc idxBit<2>
Project.unit<0>.dataChannel<15>=inst_mcp_adc idxBit<1>
Project.unit<0>.dataChannel<16>=inst_mcp_adc idxBit<0>
Project.unit<0>.dataChannel<17>=inst_mcp_adc idxBit<3>
Project.unit<0>.dataChannel<18>=inst_mcp_adc readyForNextState
Project.unit<0>.dataChannel<19>=internal_DAC_CONTROL_busy
Project.unit<0>.dataChannel<1>=internal_ADCOutput<11>
Project.unit<0>.dataChannel<20>=inst_mcp_adc scl
Project.unit<0>.dataChannel<21>=inst_mcp_adc dataToRead<6>
Project.unit<0>.dataChannel<22>=inst_mcp_adc dataToRead<5>
Project.unit<0>.dataChannel<23>=inst_mcp_adc dataToRead<4>
Project.unit<0>.dataChannel<24>=inst_mcp_adc dataToRead<3>
Project.unit<0>.dataChannel<25>=inst_mcp_adc dataToRead<2>
Project.unit<0>.dataChannel<26>=inst_mcp_adc dataToRead<1>
Project.unit<0>.dataChannel<27>=inst_mcp_adc dataToRead<0>
Project.unit<0>.dataChannel<28>=inst_mcp_adc idxCyc<1>
Project.unit<0>.dataChannel<29>=inst_mcp_adc Result<0>
Project.unit<0>.dataChannel<2>=internal_ADCOutput<10>
Project.unit<0>.dataChannel<3>=internal_ADCOutput<9>
Project.unit<0>.dataChannel<4>=internal_ADCOutput<8>
Project.unit<0>.dataChannel<5>=internal_ADCOutput<7>
Project.unit<0>.dataChannel<6>=internal_ADCOutput<6>
Project.unit<0>.dataChannel<7>=internal_ADCOutput<5>
Project.unit<0>.dataChannel<8>=internal_ADCOutput<4>
Project.unit<0>.dataChannel<9>=internal_ADCOutput<3>
Project.unit<0>.dataDepth=2048
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=30
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=inst_mcp_adc runADC
Project.unit<0>.triggerChannel<0><1>=inst_mcp_adc i_runADC
Project.unit<0>.triggerChannel<0><2>=inst_mpps_dacs WRITE_STROBE
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=3
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
Project.unit<1>.clockChannel=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface FIFO_CLOCK
Project.unit<1>.clockEdge=Rising
Project.unit<1>.dataDepth=1024
Project.unit<1>.dataEqualsTrigger=true
Project.unit<1>.dataPortWidth=8
Project.unit<1>.enableGaps=false
Project.unit<1>.enableStorageQualification=true
Project.unit<1>.enableTimestamps=false
Project.unit<1>.timestampDepth=0
Project.unit<1>.timestampWidth=0
Project.unit<1>.triggerChannel<0><0>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP4_WRITE_ENABLE
Project.unit<1>.triggerChannel<0><1>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP2_WRITE_ENABLE
Project.unit<1>.triggerChannel<0><2>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_READ_ENABLE
Project.unit<1>.triggerChannel<0><3>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_READ_ENABLE
Project.unit<1>.triggerChannel<0><4>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_flagA_in
Project.unit<1>.triggerChannel<0><5>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface usb_flagB_in
Project.unit<1>.triggerChannel<0><6>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP8_FULL
Project.unit<1>.triggerChannel<0><7>=map_readout_interfaces map_daq_fifo_layer synthesize_with_usb.map_usb_interface EP6_FULL
Project.unit<1>.triggerConditionCountWidth=0
Project.unit<1>.triggerMatchCount<0>=1
Project.unit<1>.triggerMatchCountWidth<0><0>=0
Project.unit<1>.triggerMatchType<0><0>=1
Project.unit<1>.triggerPortCount=1
Project.unit<1>.triggerPortIsData<0>=true
Project.unit<1>.triggerPortWidth<0>=8
Project.unit<1>.triggerSequencerLevels=16
Project.unit<1>.triggerSequencerType=1
Project.unit<1>.type=ilapro
