#ChipScope Core Inserter Project File Version 3.0
#Thu Oct 30 11:54:40 HST 2014
Project.device.designInputFile=C\:\\Users\\isar\\Documents\\code4\\TX9UMB-3\\ise-project\\scrod_top_A4.ngc
Project.device.designOutputFile=C\:\\Users\\isar\\Documents\\code4\\TX9UMB-3\\ise-project\\scrod_top_A4_csp.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\Users\\isar\\Documents\\code4\\TX9UMB-3\\ise-project\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=internal_*_ALL
Project.filter<11>=internal_???_ALL
Project.filter<12>=internal_TRigger*
Project.filter<13>=internal_TR*
Project.filter<14>=internal_T*
Project.filter<15>=ex_trig*
Project.filter<16>=psw*
Project.filter<17>=psw
Project.filter<18>=ram*
Project.filter<1>=wr*
Project.filter<2>=wr_*
Project.filter<3>=wr_
Project.filter<4>=EX*
Project.filter<5>=internal_EX*
Project.filter<6>=internal_READCTRL_trigger
Project.filter<7>=internal_H*
Project.filter<8>=internal_HARDWARE_TRIGGER
Project.filter<9>=internal_TRIGGER_ALL
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=map_clock_gen CLOCK_FPGA_LOGIC
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=u_SamplingLgc sstin
Project.unit<0>.dataChannel<100>=
Project.unit<0>.dataChannel<101>=
Project.unit<0>.dataChannel<102>=
Project.unit<0>.dataChannel<103>=
Project.unit<0>.dataChannel<104>=
Project.unit<0>.dataChannel<105>=
Project.unit<0>.dataChannel<106>=
Project.unit<0>.dataChannel<107>=
Project.unit<0>.dataChannel<108>=
Project.unit<0>.dataChannel<109>=
Project.unit<0>.dataChannel<10>=u_SamplingLgc wr_addrclr
Project.unit<0>.dataChannel<110>=
Project.unit<0>.dataChannel<111>=
Project.unit<0>.dataChannel<112>=
Project.unit<0>.dataChannel<113>=
Project.unit<0>.dataChannel<114>=
Project.unit<0>.dataChannel<115>=
Project.unit<0>.dataChannel<116>=
Project.unit<0>.dataChannel<117>=
Project.unit<0>.dataChannel<118>=
Project.unit<0>.dataChannel<119>=
Project.unit<0>.dataChannel<11>=u_SerialDataRout WIN_ADDR<8>
Project.unit<0>.dataChannel<120>=
Project.unit<0>.dataChannel<121>=
Project.unit<0>.dataChannel<122>=
Project.unit<0>.dataChannel<123>=
Project.unit<0>.dataChannel<124>=
Project.unit<0>.dataChannel<125>=
Project.unit<0>.dataChannel<126>=
Project.unit<0>.dataChannel<127>=
Project.unit<0>.dataChannel<12>=u_SerialDataRout WIN_ADDR<7>
Project.unit<0>.dataChannel<13>=u_SerialDataRout WIN_ADDR<6>
Project.unit<0>.dataChannel<14>=u_SerialDataRout WIN_ADDR<5>
Project.unit<0>.dataChannel<15>=u_SerialDataRout WIN_ADDR<4>
Project.unit<0>.dataChannel<16>=u_SerialDataRout WIN_ADDR<3>
Project.unit<0>.dataChannel<17>=u_SerialDataRout WIN_ADDR<2>
Project.unit<0>.dataChannel<18>=u_SerialDataRout WIN_ADDR<1>
Project.unit<0>.dataChannel<19>=u_SerialDataRout WIN_ADDR<0>
Project.unit<0>.dataChannel<1>=u_SamplingLgc MAIN_CNT<8>
Project.unit<0>.dataChannel<20>=u_SerialDataRout ASIC_NUM<3>
Project.unit<0>.dataChannel<21>=u_SerialDataRout ASIC_NUM<2>
Project.unit<0>.dataChannel<22>=u_SerialDataRout ASIC_NUM<1>
Project.unit<0>.dataChannel<23>=u_SerialDataRout ASIC_NUM<0>
Project.unit<0>.dataChannel<24>=u_SerialDataRout dout<15>
Project.unit<0>.dataChannel<25>=u_SerialDataRout dout<14>
Project.unit<0>.dataChannel<26>=u_SerialDataRout dout<13>
Project.unit<0>.dataChannel<27>=u_SerialDataRout dout<12>
Project.unit<0>.dataChannel<28>=u_SerialDataRout dout<11>
Project.unit<0>.dataChannel<29>=u_SerialDataRout dout<10>
Project.unit<0>.dataChannel<2>=u_SamplingLgc MAIN_CNT<7>
Project.unit<0>.dataChannel<30>=u_SerialDataRout dout<9>
Project.unit<0>.dataChannel<31>=u_SerialDataRout dout<8>
Project.unit<0>.dataChannel<32>=u_SerialDataRout dout<7>
Project.unit<0>.dataChannel<33>=u_SerialDataRout dout<6>
Project.unit<0>.dataChannel<34>=u_SerialDataRout dout<5>
Project.unit<0>.dataChannel<35>=u_SerialDataRout dout<4>
Project.unit<0>.dataChannel<36>=u_SerialDataRout dout<3>
Project.unit<0>.dataChannel<37>=u_SerialDataRout dout<2>
Project.unit<0>.dataChannel<38>=u_SerialDataRout dout<1>
Project.unit<0>.dataChannel<39>=u_SerialDataRout dout<0>
Project.unit<0>.dataChannel<3>=u_SamplingLgc MAIN_CNT<6>
Project.unit<0>.dataChannel<40>=u_SerialDataRout start
Project.unit<0>.dataChannel<41>=u_SerialDataRout BIT_CNT<3>
Project.unit<0>.dataChannel<42>=u_SerialDataRout BIT_CNT<2>
Project.unit<0>.dataChannel<43>=u_SerialDataRout BIT_CNT<1>
Project.unit<0>.dataChannel<44>=u_SerialDataRout BIT_CNT<0>
Project.unit<0>.dataChannel<45>=u_SerialDataRout BIT_CNT<4>
Project.unit<0>.dataChannel<46>=u_SerialDataRout fifo_wr_en
Project.unit<0>.dataChannel<47>=u_SerialDataRout internal_fifo_wr_din<22>
Project.unit<0>.dataChannel<48>=u_SerialDataRout internal_fifo_wr_din<28>
Project.unit<0>.dataChannel<49>=u_SerialDataRout internal_fifo_wr_din<29>
Project.unit<0>.dataChannel<4>=u_SamplingLgc MAIN_CNT<5>
Project.unit<0>.dataChannel<50>=u_SerialDataRout internal_fifo_wr_din<20>
Project.unit<0>.dataChannel<51>=u_SerialDataRout internal_fifo_wr_din<24>
Project.unit<0>.dataChannel<52>=u_SerialDataRout internal_fifo_wr_din<19>
Project.unit<0>.dataChannel<53>=u_SerialDataRout internal_fifo_wr_din<18>
Project.unit<0>.dataChannel<54>=u_SerialDataRout internal_fifo_wr_din<17>
Project.unit<0>.dataChannel<55>=u_SerialDataRout internal_fifo_wr_din<16>
Project.unit<0>.dataChannel<56>=u_SerialDataRout internal_fifo_wr_din<15>
Project.unit<0>.dataChannel<57>=u_SerialDataRout internal_fifo_wr_din<14>
Project.unit<0>.dataChannel<58>=u_SerialDataRout internal_fifo_wr_din<13>
Project.unit<0>.dataChannel<59>=u_SerialDataRout internal_fifo_wr_din<12>
Project.unit<0>.dataChannel<5>=u_SamplingLgc MAIN_CNT<4>
Project.unit<0>.dataChannel<60>=u_SerialDataRout internal_fifo_wr_din<11>
Project.unit<0>.dataChannel<61>=u_SerialDataRout internal_fifo_wr_din<10>
Project.unit<0>.dataChannel<62>=u_SerialDataRout internal_fifo_wr_din<9>
Project.unit<0>.dataChannel<63>=u_SerialDataRout internal_fifo_wr_din<8>
Project.unit<0>.dataChannel<64>=u_SerialDataRout internal_fifo_wr_din<7>
Project.unit<0>.dataChannel<65>=u_SerialDataRout internal_fifo_wr_din<6>
Project.unit<0>.dataChannel<66>=u_SerialDataRout internal_fifo_wr_din<5>
Project.unit<0>.dataChannel<67>=u_SerialDataRout internal_fifo_wr_din<4>
Project.unit<0>.dataChannel<68>=u_SerialDataRout internal_fifo_wr_din<3>
Project.unit<0>.dataChannel<69>=u_SerialDataRout internal_fifo_wr_din<2>
Project.unit<0>.dataChannel<6>=u_SamplingLgc MAIN_CNT<3>
Project.unit<0>.dataChannel<70>=u_SerialDataRout internal_fifo_wr_din<1>
Project.unit<0>.dataChannel<71>=u_SerialDataRout internal_fifo_wr_din<0>
Project.unit<0>.dataChannel<72>=u_ReadoutControl internal_LATCH_DONE
Project.unit<0>.dataChannel<73>=u_ReadoutControl DIG_IDLE_status
Project.unit<0>.dataChannel<74>=u_ReadoutControl SROUT_IDLE_status
Project.unit<0>.dataChannel<75>=u_ReadoutControl trigger
Project.unit<0>.dataChannel<76>=u_ReadoutControl internal_LATCH_SMP_MAIN_CNT<8>
Project.unit<0>.dataChannel<77>=u_ReadoutControl internal_LATCH_SMP_MAIN_CNT<7>
Project.unit<0>.dataChannel<78>=u_ReadoutControl internal_LATCH_SMP_MAIN_CNT<6>
Project.unit<0>.dataChannel<79>=u_ReadoutControl internal_LATCH_SMP_MAIN_CNT<5>
Project.unit<0>.dataChannel<7>=u_SamplingLgc MAIN_CNT<2>
Project.unit<0>.dataChannel<80>=u_ReadoutControl internal_LATCH_SMP_MAIN_CNT<4>
Project.unit<0>.dataChannel<81>=u_ReadoutControl internal_LATCH_SMP_MAIN_CNT<3>
Project.unit<0>.dataChannel<82>=u_ReadoutControl internal_LATCH_SMP_MAIN_CNT<2>
Project.unit<0>.dataChannel<83>=u_ReadoutControl internal_LATCH_SMP_MAIN_CNT<1>
Project.unit<0>.dataChannel<84>=u_ReadoutControl internal_LATCH_SMP_MAIN_CNT<0>
Project.unit<0>.dataChannel<85>=u_DigitizingLgc StartDig
Project.unit<0>.dataChannel<86>=u_DigitizingLgc clr_out
Project.unit<0>.dataChannel<87>=u_DigitizingLgc rd_ena_out
Project.unit<0>.dataChannel<88>=u_DigitizingLgc startramp_out
Project.unit<0>.dataChannel<89>=u_DigitizingLgc rd_ena_out
Project.unit<0>.dataChannel<8>=u_SamplingLgc MAIN_CNT<1>
Project.unit<0>.dataChannel<90>=internal_READCTRL_trigger
Project.unit<0>.dataChannel<91>=internal_EX_TRIGGER_SCROD
Project.unit<0>.dataChannel<92>=EX_TRIGGER_SCROD
Project.unit<0>.dataChannel<93>=
Project.unit<0>.dataChannel<94>=
Project.unit<0>.dataChannel<95>=
Project.unit<0>.dataChannel<96>=
Project.unit<0>.dataChannel<97>=
Project.unit<0>.dataChannel<98>=
Project.unit<0>.dataChannel<99>=
Project.unit<0>.dataChannel<9>=u_SamplingLgc MAIN_CNT<0>
Project.unit<0>.dataDepth=8192
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=92
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=u_SamplingLgc sstin
Project.unit<0>.triggerChannel<0><10>=u_DigitizingLgc StartDig
Project.unit<0>.triggerChannel<0><11>=u_DigitizingLgc rd_ena_out
Project.unit<0>.triggerChannel<0><12>=
Project.unit<0>.triggerChannel<0><13>=
Project.unit<0>.triggerChannel<0><14>=
Project.unit<0>.triggerChannel<0><15>=
Project.unit<0>.triggerChannel<0><1>=internal_EX_TRIGGER_SCROD
Project.unit<0>.triggerChannel<0><2>=u_ReadoutControl trigger
Project.unit<0>.triggerChannel<0><3>=uut_pedram WEb
Project.unit<0>.triggerChannel<0><4>=uut_pedram OEb
Project.unit<0>.triggerChannel<0><5>=u_ReadoutControl internal_LATCH_DONE
Project.unit<0>.triggerChannel<0><6>=u_SerialDataRout fifo_wr_en
Project.unit<0>.triggerChannel<0><7>=internal_READCTRL_trigger
Project.unit<0>.triggerChannel<0><8>=u_SerialDataRout start
Project.unit<0>.triggerChannel<0><9>=u_SamplingLgc wr_addrclr
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=11
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
